apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-10g-6
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/local-storage/storage/pv-10g-6
    type: ''
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
