apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-5g-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/local-storage/storage/pv-5g-2
    type: ''
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
